/**
 * Chain Support: arbitrum
 * Auto-generated by AutoDevelopmentAgent
 */

const { ethers } = require('ethers');

const arbitrumConfig = {
  name: 'arbitrum',
  rpcUrl: process.env.RPC_ARBITRUM || 'https://arbitrum.llamarpc.com',
  chainId: 0, // TODO: Set correct chain ID
  nativeCurrency: {
    name: 'ETH',
    symbol: 'ETH',
    decimals: 18
  }
};

class ArbitrumProvider {
  constructor() {
    this.provider = new ethers.JsonRpcProvider(arbitrumConfig.rpcUrl);
  }

  async getCode(address) {
    return await this.provider.getCode(address);
  }

  async getBalance(address) {
    return await this.provider.getBalance(address);
  }
}

module.exports = { ArbitrumProvider, arbitrumConfig };
