/**
 * Chain Support: base
 * Auto-generated by AutoDevelopmentAgent
 */

const { ethers } = require('ethers');

const baseConfig = {
  name: 'base',
  rpcUrl: process.env.RPC_BASE || 'https://base.llamarpc.com',
  chainId: 0, // TODO: Set correct chain ID
  nativeCurrency: {
    name: 'ETH',
    symbol: 'ETH',
    decimals: 18
  }
};

class BaseProvider {
  constructor() {
    this.provider = new ethers.JsonRpcProvider(baseConfig.rpcUrl);
  }

  async getCode(address) {
    return await this.provider.getCode(address);
  }

  async getBalance(address) {
    return await this.provider.getBalance(address);
  }
}

module.exports = { BaseProvider, baseConfig };
