/**
 * Skill: git-commit-push
 * Add, commit, and push in one command
 * Auto-generated by SkillGeneratorAgent
 */

const { execSync } = require('child_process');

class GitCommitPush {
  constructor() {
    this.name = 'git-commit-push';
    this.description = 'Add, commit, and push in one command';
  }

  execute(options = {}) {
    console.log('Executing: git-commit-push');
    
    try {
      execSync('git add -A && git commit -m "message" && git push', { 
        cwd: process.cwd(),
        stdio: 'inherit' 
      });
      return { success: true, message: 'git-commit-push completed' };
    } catch (error) {
      return { success: false, error: error.message };
    }
  }
}

module.exports = { GitCommitPush };

// CLI usage
if (require.main === module) {
  new GitCommitPush().execute();
}
