/**
 * Skill: git-last-commits
 * Show last N commits with stats
 * Auto-generated by SkillGeneratorAgent
 */

const { execSync } = require('child_process');

class GitLastCommits {
  constructor() {
    this.name = 'git-last-commits';
    this.description = 'Show last N commits with stats';
  }

  execute(options = {}) {
    console.log('Executing: git-last-commits');
    
    try {
      execSync('git log --oneline -10 --stat', { 
        cwd: process.cwd(),
        stdio: 'inherit' 
      });
      return { success: true, message: 'git-last-commits completed' };
    } catch (error) {
      return { success: false, error: error.message };
    }
  }
}

module.exports = { GitLastCommits };

// CLI usage
if (require.main === module) {
  new GitLastCommits().execute();
}
