/**
 * Skill: git-status-short
 * Quick git status with only changed files
 * Auto-generated by SkillGeneratorAgent
 */

const { execSync } = require('child_process');

class GitStatusShort {
  constructor() {
    this.name = 'git-status-short';
    this.description = 'Quick git status with only changed files';
  }

  execute(options = {}) {
    console.log('Executing: git-status-short');
    
    try {
      execSync('git status --short', { 
        cwd: process.cwd(),
        stdio: 'inherit' 
      });
      return { success: true, message: 'git-status-short completed' };
    } catch (error) {
      return { success: false, error: error.message };
    }
  }
}

module.exports = { GitStatusShort };

// CLI usage
if (require.main === module) {
  new GitStatusShort().execute();
}
