/**
 * Storage Slot Reader
 * Auto-generated by AutoDevelopmentAgent
 */

const { ethers } = require('ethers');

class SlotReader {
  constructor(provider) {
    this.provider = provider;
  }

  async readSlot(contractAddress, slot) {
    const value = await this.provider.getStorage(contractAddress, slot);
    return value;
  }

  async readMapping(contractAddress, mappingSlot, key) {
    // Calculate mapping slot
    const slotHash = ethers.keccak256(
      ethers.concat([ethers.zeroPadValue(key, 32), ethers.zeroPadValue(mappingSlot, 32)])
    );
    return await this.readSlot(contractAddress, slotHash);
  }
}

module.exports = { SlotReader };
