/**
 * Enhanced Cache
 * Auto-generated by AutoDevelopmentAgent
 */

class EnhancedCache {
  constructor() {
    this.cache = new Map();
    this.ttl = 300; // 5 minutes default
  }

  set(key, value, customTtl) {
    const expiry = Date.now() + (customTtl || this.ttl) * 1000;
    this.cache.set(key, { value, expiry });
  }

  get(key) {
    const item = this.cache.get(key);
    if (!item) return null;
    if (Date.now() > item.expiry) {
      this.cache.delete(key);
      return null;
    }
    return item.value;
  }

  cleanup() {
    const now = Date.now();
    for (const [key, item] of this.cache.entries()) {
      if (now > item.expiry) {
        this.cache.delete(key);
      }
    }
  }
}

module.exports = { EnhancedCache };
